.\" Copyright (C) 2026 TheCRatTime
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH "AtExitClean" "3" "2026\-10\-03" "TheCRatTime" "AtExit reference"
.SH NAME
\fBAtExitClean\fR \- free \fBAtExitHeader\fR struct.\&
.PP
.SH SYNOPSIS
\fB#include\fR <\fBatexit.\&h\fR>
.PP
\fBvoid AtExitFree(AtExitHeader* \fIhead\fB);\fR
.PP
.SH DESCRIPTION
Free \fIhead\fR.\&
.PP
\fIhead\fR
.RS 4
Pointer to \fBAtExitHeader\fR struct, that can be given by \fB&\fR.\&
.RE
.PP
.SH EXAMPLES
.nf
#include <atexit.h>

int main(void) {
  /* Init AtExitHeader with name test... */
  AtExitFree(test);
  return 0;
}
.fi
.PP
.SH AUTHORS
Man-page and project: TheCRatTime
.PP
.SH SEE ALSO
\fBatexit_do\fR(3), \fBInitAtExit\fR(3), \fBAtExitHeader\fR(3type)
