.\" Copyright (C) 2026 TheCRatTime
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"     http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH "defer" "3" "2026\-09\-29" "TheCRatTime" "AtExit reference"
.SH NAME
\fBdefer\fR \- macro, that expands to \fBSetAtExit\fR(3).\&
.PP
.SH SYNOPSIS
\fB#include\fR <\fBatexit.\&h\fR>
.PP
\fB#define defer(\fIhd\fB, \fIfunc\fB, \fIarg\fB) SetAtExit(\fIhd\fB, \fIfunc\fB, \fIarg\fB)\fR
.PP
.SH DESCRIPTION
\fBdefer\fR \- stolen from Go.\&
.PP
Usage: see \fBSetAtExit\fR(3)
.SH AUTHORS
Project and man\-page: TheCRatTime
.PP
.SH SEE ALSO
\fBatexit_do\fR(3), \fBInitAtExit\fR(3), \fBSetAtExit\fR(3), \fBAtExitHeader\fR(3type), \fBSetAtExit\fR(3)
