cmake_minimum_required(VERSION 3.10)
project(atexit C)
# include(CTest)
# include(CheckCCompilerFlag)

# enable_testing()

set(REAL_LIB_TYPE    STATIC)
set(REAL_BUILD_EX       OFF)
set(REAL_USE_QUOTES      ON)
set(SET_OWN_INC_PATH     "")

option(USE_SHARED   "Use shared library instead of static"         OFF)
option(BUILD_EX     "Build examples"                               OFF)
option(USE_QUOTES   "Use \"quotes\" instead of <this> in includes"  ON)
option(OWN_INC_PATH "Use own path to atexit.h"                      "")

if(NOT USE_SHARED)
  message(STATUS "Using static library")
else()
  message(STATUS "Using shared library")
  set(REAL_LIB_TYPE SHARED)
endif()

if(NOT BUILD_EX)
  message(STATUS "Not building examples")
else()
  message(STATUS "Building examples")
  set(REAL_BUILD_EX ON)
endif()

if(NOT USE_QUOTES)
  message(STATUS "Using <this>")
  set(REAL_USE_QUOTES OFF)
else()
  message(STATUS "Using \"quotes\"")
endif()

if(OWN_INC_PATH STREQUAL "" OR NOT OWN_INC_PATH)
  message(STATUS "Using path \"../include/atexit.h\"")
else()
  message(STATUS "Using path \"${OWN_INC_PATH}\"")
  set(SET_OWN_INC_PATH ${OWN_INC_PATH})
  set(REAL_USE_QUOTES ON)
endif()

add_library(atexit_do ${REAL_LIB_TYPE} src/atexit.c)
target_include_directories(atexit_do PRIVATE include)
if(REAL_USE_QUOTES)
  target_compile_options(atexit_do PRIVATE -DINC_USE_QUOTES)
endif()
if(NOT SET_OWN_INC_PATH STREQUAL "")
  target_compile_options(atexit_do PRIVATE
    -DATEXIT_PATH_TO_INC=\"${SET_OWN_INC_PATH}\")
endif()

if(REAL_BUILD_EX)
  add_subdirectory(examples)
endif()
