.TH "README" "1" "2026\-09\-28" "TheCRatTime" "atexit"
.SH NAME
\fBatexit\fR \- forget about the forgotten \fBfree\fR(3)
.PP
.SH DESCRIPTION
This is a small project for disable double free and memory leak.\&
.PP
.SS Features
\fB-\fR \fBC89\fR/\fBANSI C\fR code standard.\&
.br
\fB-\fR Minimal memory usage.\&
.PP
.SS Needed
\fB-\fR C Compiler with support C89 standard.\&
.br
\fB-\fR CMake 3.\&10 and greater
.PP
.SH BUILDING
.nf
.RS 4
# Just build
cmake \-B build
cd build/
make
.fi
.RE
.PP
.nf
.RS 4
# Fast build
cmake \-B build
cd build/
make \-j$(nproc)
.fi
.RE
.PP
.nf
.RS 4
# Use ninja
cmake -B build -G Ninja
cd build/
ninja
.fi
.RE
.PP
CMake have options:
.PP
\fBUSE_SHARED\fR
.RS 4
Use shared library instead of static.\&
.br
Default: OFF
.PP
.RE
\fBBUILD_EX\fR
.RS 4
Build examples in \fBexamples/\fR directory.\&
.br
Default: OFF
.PP
.RE
\fBUSE_QUOTES\fR
.RS 4
Use "quotes" instead of <this> in includes.\&
.br
Default: ON
.PP
.RE
\fBOWN_INC_PATH\fR
.RS 4
Use own path to atexit.\&h
.br
Default: .\&.\&/include/atexit.\&h
.PP
.RE
.SS How add to your project
That use atexit in your project, you can:
.br
1.\& Link code and library (\fBlibatexit_do.a\fR)
.nf
.RS 4
# Example:
gcc -B/path/to/libraries/ your_code.c -latexit_do -o output
.fi
.RE
.PP
2.\& Move source to project:
.nf
.RS 4
mkdir -p myproject/src
cp src/atexit.c myproject/src/
cp -r include/ myproject/
# If needed, define USE_QUOTES and OWN_INC_PATH in CMake or
# INC_USE_QUOTES and ATEXIT_PATH_TO_INC in code via #define.
.fi
.RE
.PP
.SH EXAMPLES
You can find examples in \fBexamples/\fR directory.\&
.PP
.SH LICENSE
Project is under \fBApache 2.\&0\fR license.\&
.PP
.SH AUTHORS
TheCRatTime.\&
