.TH "README" "1" "2026\-10\-05" "TheCRatTime" "atexit"
.SH NAME
\fBatexit\fR \- forget about the forgotten \fBfree\fR(3)
.PP
.SH DESCRIPTION
This is a small project to prevent double free and memory leak.\&
.PP
.SS Features
\fB-\fR \fBC89\fR/\fBANSI C\fR code standard.\&
.br
\fB-\fR Minimal memory usage.\&
.br
\fB-\fR Auto-free functions.\&
.br
\fB-\fR Auto-generation wrappers.\&
.PP
.SH QUICK START
.nf
.RS 4
#include "atexit.h"

#define MAIN_VOID
#include "main_wrapper.h"

int Main(AtExitHeader* main_atexit) {
  char* buffer = AtExitMalloc(main_atexit, 4096);
  if (!buffer) {
    return 1;
  }

  /* do something... */

  /* No need write free() */
  return 0;
}
.fi
.RE
.PP
.SS Needed
\fB-\fR C Compiler with support C89 standard.\&
.br
\fB-\fR CMake 3.\&10 and greater
.PP
.SH BUILDING
.nf
.RS 4
# Just build
cmake \-B build
cd build/
make
.fi
.RE
.PP
.nf
.RS 4
# Fast build
cmake \-B build
cd build/
make \-j$(nproc)
.fi
.RE
.PP
.nf
.RS 4
# Use ninja
cmake -B build -G Ninja
cd build/
ninja
.fi
.RE
.PP
CMake have options:
.PP
\fBUSE_SHARED\fR
.RS 4
Use shared library instead of static.\&
.br
Default: OFF
.RE
.PP
\fBBUILD_EX\fR
.RS 4
Build examples in \fBexamples/\fR directory.\&
.br
Default: OFF
.RE
.PP
\fBUSE_TESTS\fR
.RS 4
Build tests.\&
.br
Default: ON
.RE
.PP
.SS How add to your project
To use atexit in your project, you can:
.br
1.\& Link code and library (\fBlibatexit_do.a\fR)
.nf
.RS 4
# Example:
gcc -B/path/to/libraries/ your_code.c -latexit_do -o output
.fi
.RE
.PP
2.\& Move source to project:
.nf
.RS 4
mkdir -p myproject/src
cp src/*.c myproject/src/
cp -r include/ myproject/
.fi
.RE
.PP
.SH EXAMPLES
You can find examples in \fBexamples/\fR directory.\&
.PP
.SH LICENSE
Project is under \fBApache 2.\&0\fR license.\&
.PP
.SH AUTHORS
TheCRatTime.\&
